import { QList } from '../models/entities';
import { Theme } from '../types';

export enum UIEvent {
  CLICK_SETTING_BTN = 'CLICK_SETTING_BTN',
  DEFAULT_MODAL_SHOWN = 'DEFAULT_MODAL_SHOWN',
  TOAST_DISMISS_REQUESTED = 'TOAST_DISMISS_REQUESTED',
  CHANGE_THEME = 'CHANGE_THEME',
  CHANGE_GOOGLE_CLIENT_ID = 'CHANGE_GOOGLE_CLIENT_ID',
  CHANGE_GOOGLE_FOLDER_ID = 'CHANGE_GOOGLE_FOLDER_ID',
  CLICK_GOOGLE_DRIVE_IMPORT_BTN = 'CLICK_GOOGLE_DRIVE_IMPORT_BTN',
  CHANGE_QUESTION_SEARCH_KEYWORD = 'CHANGE_QUESTION_SEARCH_KEYWORD',
  TOGGLE_QUESTION_SEARCH_IS_CASE_SENSITIVE = 'TOGGLE_QUESTION_SEARCH_IS_CASE_SENSITIVE',
  CLICK_QUESTION_SEARCH_SUBMIT = 'CLICK_QUESTION_SEARCH_SUBMIT',
  CHANGE_QUESTIONS_PAGE = 'CHANGE_QUESTIONS_PAGE',
  CLICK_QLIST_SOLVE = 'CLICK_QLIST_SOLVE',
  CLICK_QLIST_EDIT = 'CLICK_QLIST_EDIT',
  CLICK_PRACTICE_START = 'CLICK_PRACTICE_START',
  CLICK_QUESTION_LIST_ROW = 'CLICK_QUESTION_LIST_ROW',
  CLICK_PRACTICE_PREV = 'CLICK_PRACTICE_PREV',
  CLICK_PRACTICE_NEXT = 'CLICK_PRACTICE_NEXT',
  CLICK_COMPLETE_ANSWER = 'CLICK_COMPLETE_ANSWER',
  PRACTICE_ANSWERED = 'PRACTICE_ANSWERED',
  PRACTICE_ANSWER_CANCELED = 'PRACTICE_ANSWER_CANCELED',
}

export interface UIEventPayloadMap {
  [UIEvent.CLICK_SETTING_BTN]: undefined;
  [UIEvent.DEFAULT_MODAL_SHOWN]: undefined;
  [UIEvent.TOAST_DISMISS_REQUESTED]: { uuid: string };
  [UIEvent.CHANGE_THEME]: { theme: Theme };
  [UIEvent.CHANGE_GOOGLE_CLIENT_ID]: { googleClientId: string };
  [UIEvent.CHANGE_GOOGLE_FOLDER_ID]: { googleFolderId: string };
  [UIEvent.CLICK_GOOGLE_DRIVE_IMPORT_BTN]: undefined;
  [UIEvent.CHANGE_QUESTION_SEARCH_KEYWORD]: { keyword: string };
  [UIEvent.TOGGLE_QUESTION_SEARCH_IS_CASE_SENSITIVE]: undefined;
  [UIEvent.CLICK_QUESTION_SEARCH_SUBMIT]: undefined;
  [UIEvent.CHANGE_QUESTIONS_PAGE]: { page: number };
  [UIEvent.CLICK_QLIST_SOLVE]: { qListId: number };
  [UIEvent.CLICK_QLIST_EDIT]: { qListId: number };
  [UIEvent.CLICK_PRACTICE_START]: { qList: QList, isShuffleQuestions: boolean, isShuffleChoices: boolean };
  [UIEvent.CLICK_QUESTION_LIST_ROW]: { questionId: number };
  [UIEvent.CLICK_PRACTICE_PREV]: undefined;
  [UIEvent.CLICK_PRACTICE_NEXT]: undefined;
  [UIEvent.CLICK_COMPLETE_ANSWER]: undefined;
  [UIEvent.PRACTICE_ANSWERED]: { practiceHistoryId: number, questionId: number, isCorrect: boolean, selectChoice: number[] };
  [UIEvent.PRACTICE_ANSWER_CANCELED]: { practiceHistoryId: number, questionId: number };
}
